### ISSUE TITLE
v4.0.2 core.js:4081 ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

### ISSUE THREAD

**Issue by cos60** [h2qutc/angular-material-components#99]
sorry that i meet this problem at v4.0.2, angular v 10.0.3, i dont konw how to resolve it. this is error at my console.
core.js:4081 ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable. at subscribeTo (subscribeTo.ts:27) at subscribeToResult (subscribeToResult.ts:36) at MergeMapSubscriber._innerSub (mergeMap.ts:148) at MergeMapSubscriber._tryNext (mergeMap.ts:141) at MergeMapSubscriber._next (mergeMap.ts:125) at MergeMapSubscriber.next (Subscriber.ts:99) at Observable._subscribe (subscribeToArray.ts:9) at Observable._trySubscribe (Observable.ts:238) at Observable.subscribe (Observable.ts:219) at MergeMapOperator.call (mergeMap.ts:100)

i use the component by this way, it can work but stil throw the error.

<mat-form-field> <mat-label > PubTime </mat-label> <input matInput [ngxMatDatetimePicker]="picker" required readonly> <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle> <ngx-mat-datetime-picker #picker></ngx-mat-datetime-picker> </mat-form-field>

**Comment by waeschinger** [comment]
I had the same issue before updating to 4.0.2. https://github.com/h2qutc/angular-material-components/issues/89   here it was solved.

**Comment by cos60** [comment]
@waeschinger My issue appeared in version 4.0.2. the error stil exit.

**Comment by irkreja** [comment]
Hi, Facing same problem here with angular 10.1.1, angular/material 10.2.1 and datetime-picker 4.0.4.

**Comment by h2qutc** [comment]
Hi All, a version v4.0.5 has already been released. That version works fine with Angular >=10.1.1 and Angular Material >=10.2.1
Please check it out. Thanks all for your support.

**Comment by polterguy** [comment]
Experiencing the same problem. Using 5.0.3 of ngx-mat-datetime-picker. Below is my Angular version(s) ...

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.1
@angular-devkit/build-angular   0.1101.1
@angular-devkit/core            11.1.1
@angular-devkit/schematics      11.1.1
@angular/cli                    11.1.1
@schematics/angular             11.1.1
@schematics/update              0.1101.1
rxjs                            6.6.3
typescript                      4.0.5

**Comment by riallandmickael** [comment]
> Experiencing the same problem. Using 5.0.3 of ngx-mat-datetime-picker. Below is my Angular version(s) ...
> 
> ## Package Version
> @angular-devkit/architect 0.1101.1
> @angular-devkit/build-angular 0.1101.1
> @angular-devkit/core 11.1.1
> @angular-devkit/schematics 11.1.1
> @angular/cli 11.1.1
> @schematics/angular 11.1.1
> @schematics/update 0.1101.1
> rxjs 6.6.3
> typescript 4.0.5

Did you find a way to correct this console error ?

**Comment by bladmoreno** [comment]
The package was working just fine and after a while stop working throwing this same error reported here.

and this error when I click on the datetimepicker:

core.js:6141 ERROR TypeError: this.datepicker.open is not a function
    at MatDatepickerToggle._open (datepicker.js:3463)
    at MatDatepickerToggle_Template_button_click_0_listener (datepicker.js:3495)
    at executeListenerWithErrorHandling (core.js:15192)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:15227)
    at HTMLButtonElement.<anonymous> (platform-browser.js:582)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:28499)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)

packages:
"@angular-material-components/datetime-picker": "^6.0.2",
    "@angular/animations": "^11.1.1",
    "@angular/cdk": "^11.1.1",
    "@angular/common": "^11.1.1",
    "@angular/compiler": "^11.1.1",
    "@angular/core": "^11.1.1",
    "@angular/forms": "^11.1.1",
    "@angular/http": "^8.0.0-beta.10",
    "@angular/material": "^11.1.1",
    "@angular/platform-browser": "^11.1.1",
    "@angular/platform-browser-dynamic": "^11.1.1",
    "@angular/router": "^11.1.1",
